/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package omoikane.elearning.Vista;

import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import omoikane.elearning.Controlador.ControladorTareas;
import omoikane.elearning.Modelo.Dao.TareaDAO;

/**
 *
 * @author ASUS
 */
public class VistaAsesor_CrearTarea extends javax.swing.JFrame {

    private ControladorTareas controlTarea;
    private VistaAsesor_Menu menuAsesor;

    /**
     * Creates new form VistaMenuAsesor
     *
     * @param controlTarea
     */
    public VistaAsesor_CrearTarea(ControladorTareas controlTarea) {
        initComponents();
        this.controlTarea = controlTarea;
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (menuAsesor != null) {
                    menuAsesor.limpiarModelo();
                    menuAsesor.listaTareas();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        bgPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        crearTareaPanel = new javax.swing.JPanel();
        IDLabel = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        tipoLabel = new javax.swing.JLabel();
        tipoCombo = new javax.swing.JComboBox<>();
        nombreLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        nombreLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionText = new javax.swing.JTextArea();
        agregarButton = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(0, 153, 153));

        tituloLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Nueva Tarea");

        crearTareaPanel.setBackground(new java.awt.Color(255, 255, 255));

        IDLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        IDLabel.setText("ID:");

        IDText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        IDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IDTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDTextKeyTyped(evt);
            }
        });

        tipoLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipoLabel.setText("Tipo:");

        tipoCombo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarea Práctica", "Examen" }));

        nombreLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombreLabel.setText("Nombre:");

        nombreText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });

        nombreLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombreLabel1.setText("Descripción:");

        descripcionText.setColumns(20);
        descripcionText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descripcionText.setRows(5);
        jScrollPane1.setViewportView(descripcionText);

        agregarButton.setBackground(new java.awt.Color(0, 153, 153));
        agregarButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agregarButton.setForeground(new java.awt.Color(255, 255, 255));
        agregarButton.setText("Agregar");
        agregarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crearTareaPanelLayout = new javax.swing.GroupLayout(crearTareaPanel);
        crearTareaPanel.setLayout(crearTareaPanelLayout);
        crearTareaPanelLayout.setHorizontalGroup(
            crearTareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearTareaPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(crearTareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearTareaPanelLayout.createSequentialGroup()
                        .addComponent(nombreLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(crearTareaPanelLayout.createSequentialGroup()
                        .addGroup(crearTareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLabel)
                            .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel))
                        .addGap(110, 110, 110)
                        .addGroup(crearTareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crearTareaPanelLayout.createSequentialGroup()
                                .addComponent(tipoLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tipoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1)
                    .addComponent(nombreText))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearTareaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarButton)
                .addGap(184, 184, 184))
        );
        crearTareaPanelLayout.setVerticalGroup(
            crearTareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearTareaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crearTareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(tipoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crearTareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarButton)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(crearTareaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tituloLabel)
                .addGap(10, 10, 10)
                .addComponent(crearTareaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
    }//GEN-LAST:event_nombreTextActionPerformed

    private void agregarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarButtonMouseClicked
        int idTarea = getID();
        String nombre = getNombre();
        String descripcion = getDescripcion();
        String tipo = getTipo();

        //Comprueba que todos los campos esten llenados
        if ((idTarea == 0) || (nombre.equals("")) || (descripcion.equals(""))) {
            System.out.println("Hay algunos vacios");
            JOptionPane.showMessageDialog(null, "Todos los campos deben ser llenados.", "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
        } else if (!controlTarea.validarID(getID())) {
            JOptionPane.showMessageDialog(null, "Ya existe una tarea con esta ID. Ingrese una nueva.", "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
        } else if (controlTarea.crearTarea(idTarea, nombre, descripcion, tipo)) {
            System.out.println("Se lleno bien");
            JOptionPane.showMessageDialog(null, "Tarea agregada correctamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo crear la Tarea. Intente de nuevo.", "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarButtonMouseClicked

    private void IDTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDTextKeyTyped
    }//GEN-LAST:event_IDTextKeyTyped

    private void IDTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDTextKeyPressed
    }//GEN-LAST:event_IDTextKeyPressed

    private void IDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDTextKeyReleased
        String texto = IDText.getText();

        // Reemplaza todo lo que no sea dígito
        texto = texto.replaceAll("\\D", "");
        IDText.setText(texto);
    }//GEN-LAST:event_IDTextKeyReleased

    public int getID() {
        boolean esValido = IDText.getText().equals("");
        return !esValido ? parseInt(IDText.getText()) : 0;
    }

    public String getTipo() {
        boolean esTarea = tipoCombo.getSelectedIndex() == 0;
        return esTarea ? "TareaPractica" : tipoCombo.getSelectedItem().toString();
    }

    public String getNombre() {
        return nombreText.getText();
    }

    public String getDescripcion() {
        return descripcionText.getText();
    }

    public void setMenuAsesor(VistaAsesor_Menu menu) {
        this.menuAsesor = menu;
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDText;
    private javax.swing.JButton agregarButton;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JPanel crearTareaPanel;
    private javax.swing.JTextArea descripcionText;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JTextField nombreText;
    private javax.swing.JComboBox<String> tipoCombo;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
