/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package omoikane.elearning.Vista;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import omoikane.elearning.Controlador.ControladorTareas;

/**
 *
 * @author ASUS
 */
public class VistaAsesor_Menu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuAsesor
     *
     * @param crearTarea
     */
    private VistaAsesor_CrearTarea crearTarea;
    private ControladorTareas controladorTareas;

    public VistaAsesor_Menu(ControladorTareas controladorTareas) {
        this.crearTarea = crearTarea;
        this.controladorTareas = controladorTareas;
        initComponents();
        limpiarModelo();
        listaTareas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        addTareaButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        calificarButton = new javax.swing.JButton();
        bienvenidoLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        ListaPanel = new javax.swing.JPanel();
        listaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tareasList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(0, 153, 153));

        addTareaButton.setBackground(new java.awt.Color(0, 153, 153));
        addTareaButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addTareaButton.setForeground(new java.awt.Color(255, 255, 255));
        addTareaButton.setText("Crear Tarea");
        addTareaButton.setBorder(null);
        addTareaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTareaButtonMouseClicked(evt);
            }
        });

        salirButton.setBackground(new java.awt.Color(0, 153, 153));
        salirButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        salirButton.setForeground(new java.awt.Color(255, 255, 255));
        salirButton.setText("Salir");
        salirButton.setBorder(null);
        salirButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirButtonMouseClicked(evt);
            }
        });

        calificarButton.setBackground(new java.awt.Color(0, 153, 153));
        calificarButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        calificarButton.setForeground(new java.awt.Color(255, 255, 255));
        calificarButton.setText("Calificar Tarea");
        calificarButton.setBorder(null);
        calificarButton.setEnabled(false);

        bienvenidoLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenidoLabel.setText("Bienvenido");

        nombreLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("{user}");

        ListaPanel.setBackground(new java.awt.Color(255, 255, 255));

        listaLabel.setBackground(new java.awt.Color(255, 255, 255));
        listaLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        listaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listaLabel.setText("Lista de Tareas");

        tareasList.setBorder(null);
        tareasList.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tareasList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tareasList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tareasListMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tareasListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tareasList);

        javax.swing.GroupLayout ListaPanelLayout = new javax.swing.GroupLayout(ListaPanel);
        ListaPanel.setLayout(ListaPanelLayout);
        ListaPanelLayout.setHorizontalGroup(
            ListaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        ListaPanelLayout.setVerticalGroup(
            ListaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addComponent(bienvenidoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addTareaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(salirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(calificarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bienvenidoLabel)
                    .addComponent(nombreLabel))
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(addTareaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calificarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ListaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTareaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTareaButtonMouseClicked
        crearTarea = new VistaAsesor_CrearTarea(controladorTareas);

        crearTarea.setMenuAsesor(this); 
        crearTarea.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        crearTarea.setLocationRelativeTo(null);
        crearTarea.setVisible(true);
    }//GEN-LAST:event_addTareaButtonMouseClicked

    private void tareasListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tareasListMouseClicked

    }//GEN-LAST:event_tareasListMouseClicked

    private void tareasListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tareasListMousePressed
        calificarButton.setEnabled(true);
    }//GEN-LAST:event_tareasListMousePressed

    private void salirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirButtonMouseClicked

    public void listaTareas() {
        DefaultListModel modelo = (DefaultListModel) tareasList.getModel();

        for (String tarea : controladorTareas.filtrarTareas()) {
            modelo.addElement(tarea);
        }
    }

    public void limpiarModelo() {
        DefaultListModel modelo = new DefaultListModel();
        tareasList.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListaPanel;
    private javax.swing.JButton addTareaButton;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JButton calificarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listaLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton salirButton;
    private javax.swing.JList<String> tareasList;
    // End of variables declaration//GEN-END:variables
}
