/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package omoikane.elearning.Vista;

import java.awt.Color;
import static java.lang.Integer.parseInt;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import omoikane.elearning.Controlador.ControladorTareas;
import omoikane.elearning.Controlador.ControladorUsuarios;
import omoikane.elearning.Modelo.Dao.CalificacionDAO;
import omoikane.elearning.Modelo.Dao.TareaDAO;

/**
 *
 * @author aczay
 */
public class VistaLogIn extends javax.swing.JFrame {

    TareaDAO tareaDAO;
    CalificacionDAO calificacionDAO = new CalificacionDAO();

    ControladorTareas controladorTareas;
    ControladorUsuarios controladorUsuarios;

    VistaAsesor_Menu menuAsesor;
    VistaEstudiante_Menu menuEstudiante;

    /**
     * Creates new form Vista
     *
     * @param controladorUsuarios
     */
    public VistaLogIn(ControladorUsuarios controladorUsuarios) {
        this.controladorUsuarios = controladorUsuarios;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        IniciarSesionLabel = new javax.swing.JLabel();
        usarLabel = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passText = new javax.swing.JPasswordField();
        accederButton = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Omoikane Learning");
        setBackground(new java.awt.Color(0, 153, 153));

        BGPanel.setBackground(new java.awt.Color(0, 153, 153));
        BGPanel.setForeground(new java.awt.Color(255, 255, 255));

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));

        IniciarSesionLabel.setBackground(new java.awt.Color(255, 255, 255));
        IniciarSesionLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IniciarSesionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarSesionLabel.setText("Iniciar Sesión");

        usarLabel.setBackground(new java.awt.Color(255, 255, 255));
        usarLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        usarLabel.setText("Usuario:");

        userText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userText.setForeground(new java.awt.Color(204, 204, 204));
        userText.setText("Ingresa ID de usuario");
        userText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTextMousePressed(evt);
            }
        });
        userText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userTextKeyTyped(evt);
            }
        });

        passLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passLabel.setForeground(new java.awt.Color(51, 51, 51));
        passLabel.setText("Contraseña:");
        passLabel.setToolTipText("");

        passText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passText.setForeground(new java.awt.Color(204, 204, 204));
        passText.setText("123456789");
        passText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTextMousePressed(evt);
            }
        });
        passText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passTextKeyTyped(evt);
            }
        });

        accederButton.setBackground(new java.awt.Color(0, 153, 153));
        accederButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        accederButton.setForeground(new java.awt.Color(255, 255, 255));
        accederButton.setText("Acceder");
        accederButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IniciarSesionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userText, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usarLabel)
                            .addComponent(passLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(passText))
                .addContainerGap())
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(accederButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IniciarSesionLabel)
                .addGap(22, 22, 22)
                .addComponent(usarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accederButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tituloLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("OMOIKANE LEARNING");

        javax.swing.GroupLayout BGPanelLayout = new javax.swing.GroupLayout(BGPanel);
        BGPanel.setLayout(BGPanelLayout);
        BGPanelLayout.setHorizontalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        BGPanelLayout.setVerticalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accederButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederButtonActionPerformed
        int user = getUser();
        String pass = gerPass();

        //Comprueba que todos los campos esten llenados
        if (user == 0) {
            System.out.println("Hay algunos campos vacios");
            JOptionPane.showMessageDialog(null, "Todos los campos deben ser llenados.", "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
        } else if (!controladorUsuarios.validarUser(user)) {
            JOptionPane.showMessageDialog(null, "Usuario no Encontrado.", "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
        } else if (!controladorUsuarios.validarPass(user, pass)) {
            JOptionPane.showMessageDialog(null, "Contraseña Incorrecta.", "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
        } else if(controladorUsuarios.getTipo(user).equals("Asesor")){
            System.out.println(controladorUsuarios.getTipo(user));
            initAsesor(user);
            this.dispose();
        } else {
            initEstudiante(user);
            this.dispose();
        }
    }//GEN-LAST:event_accederButtonActionPerformed

    private void userTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextKeyTyped
        if (userText.getText().equals("Ingresa ID de usuario")) {
            userText.setText("");
            userText.setForeground(Color.black);
        }

        if (String.valueOf(passText.getPassword()).isEmpty()) {
            passText.setText("123456789");
            passText.setForeground(Color.decode("#E3E3E3"));
        }
    }//GEN-LAST:event_userTextKeyTyped

    private void passTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTextKeyTyped
        if (String.valueOf(passText.getPassword()).equals("123456789")) {
            passText.setText("");
            passText.setForeground(Color.black);
        }

        if (userText.getText().isEmpty()) {
            userText.setText("Ingresa ID de usuario");
            userText.setForeground(Color.decode("#E3E3E3"));
        }
    }//GEN-LAST:event_passTextKeyTyped

    private void userTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextMousePressed
        if (userText.getText().equals("Ingresa ID de usuario")) {
            userText.setText("");
            userText.setForeground(Color.black);
        }

        if (String.valueOf(passText.getPassword()).isEmpty()) {
            passText.setText("123456789");
            passText.setForeground(Color.decode("#E3E3E3"));
        }
    }//GEN-LAST:event_userTextMousePressed

    private void passTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTextMousePressed
        if (String.valueOf(passText.getPassword()).equals("123456789")) {
            passText.setText("");
            passText.setForeground(Color.black);
        }

        if (userText.getText().isEmpty()) {
            userText.setText("Ingresa ID de usuario");
            userText.setForeground(Color.decode("#E3E3E3"));
        }
    }//GEN-LAST:event_passTextMousePressed

    private void userTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextKeyReleased
        String texto = userText.getText();

        // Reemplaza todo lo que no sea dígito
        texto = texto.replaceAll("\\D", "");
        userText.setText(texto);
    }//GEN-LAST:event_userTextKeyReleased

    private int getUser() {
        boolean esValido = userText.getText().equals("") || userText.getText().equals("Ingresa ID de usuario");
        return !esValido ? parseInt(userText.getText()) : 0;
    }

    private String gerPass() {
        return String.valueOf(passText.getPassword());
    }

    private void initAsesor(int user) {
        tareaDAO = new TareaDAO(controladorUsuarios.getIdUser(user));
        System.out.println(tareaDAO.getIDUsuario());
        controladorTareas = new ControladorTareas(tareaDAO, calificacionDAO);

        menuAsesor = new VistaAsesor_Menu(controladorTareas);
        menuAsesor.nameUser(controladorUsuarios.getNameUser(user));
        menuAsesor.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        menuAsesor.pack();
        menuAsesor.setLocationRelativeTo(null);
        menuAsesor.setVisible(true);
    }

    private void initEstudiante(int user) {
        menuEstudiante = new VistaEstudiante_Menu();
        menuEstudiante.nameUser(controladorUsuarios.getNameUser(user));
        menuEstudiante.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        menuEstudiante.pack();
        menuEstudiante.setLocationRelativeTo(null);
        menuEstudiante.setVisible(true);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGPanel;
    private javax.swing.JLabel IniciarSesionLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton accederButton;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel usarLabel;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
